name: draft-release
on:
  pull_request:
    types: [closed]
jobs:
  draft-release:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged == true && github.base_ref == 'main'
    steps:
      - name: Release drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: draft-release-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}