name: GitHub Pull Request Demo
run-name: ${{ github.actor }} Requested Pull Request GitHub Actions 🚀
on:
  push:
    branches:
      - 'coin-*'
      - 'feature-*'
jobs:
  Test-With-Gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set Timezone to Asia/Seoul
        run: |
          sudo ln -snf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
          echo "Asia/Seoul" | sudo tee /etc/timezone
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
 
      # Gradle test를 실행한다
      - name: Test with Gradle
        run: ./gradlew --info test
        shell: bash